### ISSUE TITLE
Dressage Extensions Ads or specific URLs

### ISSUE THREAD

**Issue by dressagetrainingonline** [aimMediaDto/DTO#44]
Mathew is there a way to remove ads from specific videos? I'd like to promote 3 videos and want their thumbnails to load instead of an ad. Right now the Dressage Extension ads show up on these three; 

Michael Klimke- 5 year old, creating correct back to front contact, from your position
https://dressagetrainingonline.com/michael-klimke-10-12-17-five-year-old-v3.html#

Debbie McDonald- steady in the hand, lighter in the contact
https://dressagetrainingonline.com/11-2010-debbie-mcdonald-training-level-getting-the-horse-lighter-in-the-hand-v2.html#

Janet Foy- 2017 Through the Levels, breaking down test riding and common mistakes
https://dressagetrainingonline.com/janet-foy-02-23-17-dressage-through-the-levels-2017-training-v2.html

Can you remove that?

**Comment by dressagetrainingonline** [comment]
We need to make it as easy as possible for people to understand that they just click on the video to watch it and seeing an ad that won't go away unless you click it isn't ok. I'm sending out emails to non-matching members from the same set you worked on for matching so we are going to try and gain new members thus the site needs to be as easy to navigate as possible and the videos at easy to understand how to watch as possible. Thanks!

**Comment by itekk** [comment]
Working on this, will push it live on Monday.

**Comment by dressagetrainingonline** [comment]
Thanks! I'll prep my marketing email for Tuesday then.

**Comment by itekk** [comment]
Done.
1) Login to admin side.
2) Go to "Manage Video" section under "Object / Video Management" tab on left navigation.
3) Select "Add Video" or "Edit Video".
4) "Advertisements" drop down is default "Enable". You can select "Disable" to avoid advertisements before the video.
5) Disabled advertisements for above 3 videos.

**Comment by dressagetrainingonline** [comment]
I did that AND if you disable every ad then no ads show and it's a blank screen with no play window and people STILL won't know if they click that blank screen eventually a video player will open. The video player needs to be seen from the VERY BEGINNING WHEN SOMEONE CLICKS TO WATCH. This has to be easier for members please!

**Comment by itekk** [comment]
If advertisement is disable, then the player will load with thumbnail on page load. Screenshot is attached.

![video](https://user-images.githubusercontent.com/9421142/34194226-a3729e04-e57d-11e7-8093-b666500e7ad5.png)

**Comment by dressagetrainingonline** [comment]
That's PERFECT!!!!! Please do!
